### ISSUE TITLE
Cookie Banner

### ISSUE THREAD

**Issue by nikschen** [nikschen/ProTec#35]
Zustimmung oder Ablehnung von Cookies als Auswahl, nach Auswahl speicherung im cookie, wenn erlaubt, ansonsten wirds bei jedem Webseitenzugriff angezeigt

**Comment by Thom-Mon** [comment]
Cookie Rückfrage ergänzt, in einfacher Form als Javascript element, man bekommt unten am Footer den Hinweis, dass Cookies verwendet werden, und man dem automatisch zustimmt, wenn man die Seite nutzt. 

Man kann auf "Verstanden" klicken, um den banner für einen Tag verschwinden zu lassen.


Noch nicht closed, weil die php Variante noch fehlt...
